### PR TITLE
For Specimin github action, use specimin copy of the submitted PR

### PR DESCRIPTION
**Pull request by tahiat**

### CODE REVIEW

**Comment by tahiat** [comment]
Professor, When a PR is made in specimin repository, the evaluation script should be tested on the specimin copy of that PR. Here, the evaluation script will use the specimin copy that is checked out by the specimin ci/cd (job name: Checkout project sources)

**Comment by kelloggm** [comment]
@tahiat rather than make these changes, why not just set the `$SPECIMIN` environment variable in Specimin's CI script? That shouldn't require changes to the evaluation script.

(by the way, good catch. I feel foolish that I didn't notice this problem!)

**Comment by tahiat** [comment]
Professor, don't know why that did not come to my mind. changing in the ci pipeline...

**Comment by tahiat** [comment]
Setting the env variable in CI pipeline. Change not required.

**Pull request closed without merging**
